spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: file:///D:/JavaPrograms/vcasino-config
#          uri: https://github.com/vadof/vcasino-config.git
#          username: ${GIT_USERNAME}
#          password: ${GIT_PASSWORD}
          searchPaths: config
          clone-on-start: true

server:
  port: 8888  # Default port for config server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # Eureka server URL (if using Eureka)
  instance:
    preferIpAddress: true

