version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:16rc1
    networks:
      - vcasino
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    networks:
      - vcasino
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:admin@postgres:5432/postgres?sslmode=disable
      - PG_EXPORTER_AUTO_DISCOVER_DATABASES=true
    ports:
      - "9187:9187"
    depends_on:
      - postgres

  redis:
    container_name: redis
    image: redis:7.4
    networks:
      - vcasino
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "my_password"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-h", "localhost", "-p", "6379", "PING" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
      disable: false

  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.9.2
    networks:
      - vcasino
    restart: no
    ports:
      - "2181:2181"
    healthcheck:
      test: nc -z 127.0.0.1 2181 || exit -1
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.7.0
    networks:
      - vcasino
    restart: no
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    healthcheck:
      test: kafka-topics --bootstrap-server localhost:9092 --list
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5

  kafkaui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.7.2
    networks:
      - vcasino
    restart: no
    ports:
      - "8989:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit -1
      interval: 10s
      timeout: 5s
      start_period: 60s
      retries: 5

  prometheus:
    container_name: prometheus
    networks:
      - vcasino
    image: prom/prometheus:v2.35.0
    ports:
      - '9090:9090'
    volumes:
      - ../../observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:8.5.2
    networks:
      - vcasino
    user: root
    ports:
      - '3000:3000'
    links:
      - prometheus:prometheus
    volumes:
      - ../../observability/grafana:/var/lib/grafana
      - ../../observability/grafana/dashboards:/var/lib/grafana/dashboards
      - ../../observability/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_INSTALL_PLUGINS=redis-app

  mail-dev:
    container_name: mail-dev
    image: maildev/maildev
    networks:
      - vcasino
    restart: no
    ports:
      - "1080:1080"
      - "1025:1025"

  localstack:
    image: localstack/localstack:4.3.0
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "localstack_data:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  db:
    driver: local
  redis_data:
    driver: local
  kafka_data:
    driver: local
  localstack_data:
    driver: local

networks:
  vcasino:
    driver: bridge
