server:
  port: 8500
  address: 0.0.0.0

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  threads:
    virtual:
      enabled: true
  application:
    name: notification-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

config:
  client-url: ${CLIENT_URL}
  jwt:
    public-key-path: ${PUBLIC_KEY_PATH}
  redis:
    hostName: ${REDIS_HOSTNAME}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}