server:
  port: 300

spring:
  application:
    name: auth-service
  cloud:
    config:
      uri: http://localhost:8888
      profile: default  # Profile to use, can be adjusted as needed
      label: main  # Branch name, if using a specific branch in your Git repo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
