version: '3.9'

services:

  postgres:
    image: postgres:16rc1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
