version: '3.9'

services:
  postgres:
    image: postgres:16rc1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=vcasino
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/vcasino

volumes:
  data:
    driver: local