server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

config:
  production: ${PRODUCTION}
  client-url: ${CLIENT_URL}
  jwt:
    public-key-path: ${PUBLIC_KEY_PATH}
