server:
  port: 8080

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

config:
  production: ${PRODUCTION}
  client-url: ${CLIENT_URL}
  admin-client-url: ${ADMIN_CLIENT_URL}
  jwt:
    public-key-path: ${PUBLIC_KEY_PATH}
