server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  #      globalcors:
  #        cors-configurations:
  #          '[/**]':
  #            allowedOrigins: '*'
  #            allowedHeaders: '*'
  #            allowedMethods:
  #              - GET
  #              - POST

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: fhsjwHWjhwqLxTgpV+nBMpM3XB0jgETR0vWsyRFV9oQ=
  expirationMs: 900000 # 15min
  refreshExpirationMs: 86400000 # 1day