server:
  port: 8499

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: odds-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bet_service?tcpKeepAlive=true
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      validation-timeout: 1000
      idle-timeout: 30000
      leak-detection-threshold: 5000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:29092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


chrome:
  driver:
    path: "C:\\chromedriver\\chromedriver.exe"
