server:
  port: 8210

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: clicker-data-service
  datasource:
    url: jdbc:postgresql://localhost:5432/clicker_service
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      validation-timeout: 1000
      idle-timeout: 30000
      leak-detection-threshold: 5000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 5000
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
  kafka:
    bootstrap-servers: localhost:29092

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
