server:
  port: 8400
  address: 0.0.0.0

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  threads:
    virtual:
      enabled: true
  application:
    name: wallet-service
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:5432/${DB_NAME:wallet_service}?tcpKeepAlive=true
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      validation-timeout: 1000
      idle-timeout: 30000
      leak-detection-threshold: 5000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

config:
  redis:
    hostName: ${REDIS_HOSTNAME}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
