{
 "title": "VCasino System Overview",
 "description": "VCasino System Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(http_server_requests_seconds_count, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{job=\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RPS by URI",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(uri) (irate(http_server_requests_seconds_count{job=\"$job\", instance=~\"$instance\", uri=~\"/api.*\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "RPS by instance",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(http_server_requests_seconds_count{job=\"$job\", instance=~\"$instance\", uri=~\"/api.*\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(status) (irate(http_server_requests_seconds_count{job=\"$job\", instance=~\"$instance\", uri=~\"/api.*\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "AVG Response Time (by instance)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(instance) (increase(http_server_requests_seconds_sum{job=\"$job\", instance=~\"$instance\", uri=~\"/api.*\"}[$__rate_interval]))\n / \n(sum by(instance) (increase(http_server_requests_seconds_count{job=\"$job\", instance=~\"$instance\", uri=~\"/api.*\"}[$__rate_interval])) != 0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "AVG Response Time (by outcome)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(outcome) (increase(http_server_requests_seconds_sum{job=\"$job\", instance=~\"$instance\", uri=~\"/api.*\"}[$__rate_interval]))\n / \n (sum by(outcome) (increase(http_server_requests_seconds_count{job=\"$job\", instance=~\"$instance\", uri=~\"/api.*\"}[$__rate_interval])) != 0)",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "CPU Usage by instance",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (process_cpu_usage{job=\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}