global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend-services'
    eureka_sd_configs:
      - server: "http://host.docker.internal:8761/eureka"
        refresh_interval: 15s
    metrics_path: '/actuator/prometheus'
    relabel_configs:
      - source_labels: [__meta_eureka_app_name]
        regex: "(CLICKER-SERVICE|CLICKER-DATA-SERVICE|USER-SERVICE|WALLET-SERVICE|NOTIFICATION-SERVICE|BET-SERVICE|API-GATEWAY)"
        target_label: application
      - source_labels: [__meta_eureka_instance_id]
        separator: ":"
        target_label: instance

  - job_name: 'postgres'
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]
        labels:
          application: 'PostgreSQL'
