server:
  port: 8300

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  threads:
    virtual:
      enabled: true
  application:
    name: bet-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bet_service?tcpKeepAlive=true
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      validation-timeout: 1000
      idle-timeout: 30000
      leak-detection-threshold: 5000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  kafka:
    bootstrap-servers: localhost:29092
  cloud:
    openfeign:
      httpclient:
        enabled: false
      okhttp:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

config:
  client-url: ${CLIENT_URL}
  s3:
    bucket: local-bucket
    endpoint: http://localhost:4566
    region: us-east-1
    access-key: test
    secret-key: test
  redis:
    hostName: ${REDIS_HOSTNAME}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
