version: '3.9'

services:


  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: postgres:16rc1
    networks:
      - vcasino
    environment:
      - APP_ENV=${APP_ENV}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s


  eureka-server:
    container_name: ${EUREKA_CONTAINER_NAME}
    build: ../eureka-server/.
    networks:
      - vcasino
    ports:
      - '${EUREKA_PORT}:${EUREKA_PORT}'
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://eureka-server:${EUREKA_PORT}/actuator/health | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  config:
    container_name: ${CONFIG_CONTAINER_NAME}
    networks:
      - vcasino
    build: ../config/.
    ports:
      - '${CONFIG_PORT}:${CONFIG_PORT}'
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=${CONFIG_SPRING_CLOUD_CONFIG_SERVER_GIT_URI}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME=${CONFIG_SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD=${CONFIG_SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://${EUREKA_INSTANCE_HOSTNAME}:${EUREKA_PORT}/eureka
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB}
#      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
#      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
#      - EUREKA_INSTANCE_HOSTNAME=${EUREKA_INSTANCE_HOSTNAME}
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://config:${CONFIG_PORT}/actuator/health | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  authentication:
    container_name: ${AUTHENTICATION_CONTAINER_NAME}
    build: ../authentication/.
    networks:
      - vcasino
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://${EUREKA_INSTANCE_HOSTNAME}:${EUREKA_PORT}/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config:${CONFIG_PORT}
#      - EUREKA_INSTANCE_HOSTNAME=${EUREKA_INSTANCE_HOSTNAME}
    depends_on:
      postgres:
        condition: service_healthy
      config:
        condition: service_healthy

networks:
  vcasino:
    driver: bridge

volumes:
  prod:
    driver: local
  test:
    driver: local

#SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
# POSTGRES_USER=postgres
# POSTGRES_PASSWORD=admin
# POSTGRES_DB=vcasino