server:
  port: 8110

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  kafka:
    bootstrap-servers: localhost:29092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

jwt:
  expirationMs: ${JWT_EXPIRATION}
  refreshExpirationMs: ${JWT_REFRESH_EXPIRATION}
  keys:
    path: ${KEYS_PATH}
