server:
  port: 305

spring:
  application:
    name: finance-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

exchangerate:
  api:
    key: a6f4b8690399b524bdf841e4